package proyecto1;


import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.*;


/**
 *
 * @author eliss
 */
public class Lectura extends javax.swing.JFrame {

    JFileChooser seleccionado  =new JFileChooser();
    File archivo;
    GestioDoc op=new GestioDoc();
    
    
    /**
     * Creates new form lectura
     */
    public Lectura() {
        initComponents();
          ImageIcon imagen1 = new ImageIcon(getClass().getResource("/imagenes/escudo_fi_color.png"));
         Icon fondo1 =new ImageIcon(imagen1.getImage().getScaledInstance(IE.getWidth(),IE.getHeight(),Image.SCALE_DEFAULT));
       IE.setIcon(fondo1);
       this.repaint();
       
       this.setTitle("Compilador AVEL");
       
       this.setExtendedState(WIDTH);
       Image ico= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/escudo_fi_color.png"));
        this.setIconImage(ico);
        //this.setExtendedState(Menu.MAXIMIZED_BOTH);
        setSize(1400,1200);
        
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"));
        Icon fondo3 =new ImageIcon(imagen3.getImage().getScaledInstance(fondo2.getWidth(),fondo2.getHeight(),Image.SCALE_DEFAULT));
       fondo2.setIcon(fondo3);
       this.repaint();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaText = new javax.swing.JTextArea();
        IE = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        save1 = new javax.swing.JButton();
        next1 = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtAreaText.setColumns(20);
        txtAreaText.setRows(5);
        jScrollPane1.setViewportView(txtAreaText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 210, 1050, 500);
        getContentPane().add(IE);
        IE.setBounds(1170, 20, 190, 230);

        select.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        select.setText("Seleccionar Archivo");
        select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectMouseClicked(evt);
            }
        });
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        getContentPane().add(select);
        select.setBounds(170, 760, 290, 90);

        save1.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        save1.setText("Guardar Cambios");
        save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save1MouseClicked(evt);
            }
        });
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        getContentPane().add(save1);
        save1.setBounds(590, 760, 290, 90);

        next1.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        next1.setText("Regresar");
        next1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next1MouseClicked(evt);
            }
        });
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        getContentPane().add(next1);
        next1.setBounds(1050, 760, 230, 90);

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(fondo2);
        fondo2.setBounds(-410, -290, 1880, 1320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed

       
           
    }//GEN-LAST:event_selectActionPerformed

    private void selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMouseClicked
        Menu proyect=new Menu();
        proyect.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_selectMouseClicked

    private void next1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_next1MouseClicked

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed

        Menu proyect=new Menu();
        proyect.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_next1ActionPerformed

    private void save1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1MouseClicked
             
    }//GEN-LAST:event_save1MouseClicked

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed

        if(seleccionado.showDialog(null, "Guardar archivo")== JFileChooser.APPROVE_OPTION){
          archivo=seleccionado.getSelectedFile();
          if(archivo.getName().endsWith("txt")){
              String contenido= txtAreaText.getText();
              String respuesta = op.GuardarArchivo(archivo, contenido);
              if(respuesta!=null){
                  JOptionPane.showMessageDialog(null, "Se guardo correctamente el contenido", "SAVE", JOptionPane.WARNING_MESSAGE);
              }else{
                  JOptionPane.showMessageDialog(null, "Error, documento no encontrado. Intenta de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
              }
          }else{
              JOptionPane.showMessageDialog(null, "Error, documento no encontrado. Intenta de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
          }
        }
    }//GEN-LAST:event_save1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IE;
    private javax.swing.JLabel fondo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next1;
    private javax.swing.JButton save1;
    private javax.swing.JButton select;
    private javax.swing.JTextArea txtAreaText;
    // End of variables declaration//GEN-END:variables
}
