package proyecto1;


import proyecto1.Lectura;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eliss
 */
public class Menu extends javax.swing.JFrame {
GestioDoc op=new GestioDoc();
    /**
     * Creates new form proyecto
     */
    public Menu() {
        initComponents();
        
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/imagenes/escudo_fi_color.png"));
        Icon fondo1 =new ImageIcon(imagen1.getImage().getScaledInstance(IE.getWidth(),IE.getHeight(),Image.SCALE_DEFAULT));
       IE.setIcon(fondo1);
       this.repaint();
       
       this.setTitle("Compilador AVEL");
       this.setLocationRelativeTo(Menu.this);
       this.setExtendedState(WIDTH);
       Image ico= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/escudo_fi_color.png"));
        this.setIconImage(ico);
        //this.setExtendedState(Menu.MAXIMIZED_BOTH);
        setSize(1400,1200);
        
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"));
        Icon fondo2 =new ImageIcon(imagen2.getImage().getScaledInstance(fondo.getWidth(),fondo.getHeight(),Image.SCALE_DEFAULT));
       fondo.setIcon(fondo2);
       this.repaint();
       
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IE = new javax.swing.JLabel();
        leer = new javax.swing.JButton();
        doc = new javax.swing.JButton();
        Texto1 = new javax.swing.JLabel();
        ejecutar = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(IE);
        IE.setBounds(1060, 20, 230, 230);

        leer.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        leer.setText("Visualizar");
        leer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leerMouseClicked(evt);
            }
        });
        leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerActionPerformed(evt);
            }
        });
        getContentPane().add(leer);
        leer.setBounds(490, 560, 230, 90);

        doc.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        doc.setText("Sobre el programa ");
        doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docActionPerformed(evt);
            }
        });
        getContentPane().add(doc);
        doc.setBounds(850, 560, 270, 90);

        Texto1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Texto1.setForeground(new java.awt.Color(255, 255, 255));
        Texto1.setText("Ingresa el nombre del archivo ");
        getContentPane().add(Texto1);
        Texto1.setBounds(140, 170, 490, 100);

        ejecutar.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        ejecutar.setText("Ejecutar");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });
        getContentPane().add(ejecutar);
        ejecutar.setBounds(100, 560, 240, 90);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(280, 310, 560, 80);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1390, 1040);

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(fondo1);
        fondo1.setBounds(0, 0, 1390, 1040);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        String file = name.getText();
        op.Lectura(file);
        
    }//GEN-LAST:event_ejecutarActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        
    }//GEN-LAST:event_nameActionPerformed

    private void leerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerActionPerformed

                  Lectura lect=new Lectura();
                  lect.setVisible(true);
                  this.dispose();
              
    }//GEN-LAST:event_leerActionPerformed

    private void docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docActionPerformed

    private void leerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leerMouseClicked
      
    }//GEN-LAST:event_leerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IE;
    private javax.swing.JLabel Texto1;
    private javax.swing.JButton doc;
    private javax.swing.JButton ejecutar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JButton leer;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
